[workspace]
channels = ["conda-forge", "bioconda", "pypi"]
name = "stunning-disco"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
networkx = ">=3.5,<4"
pandas = ">=2.3.3,<3"
numpy = ">=2.3.4,<3"
matplotlib = ">=3.10.7,<4"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.7.2,<2"
scipy = ">=1.16.3,<2"
